### ISSUE TITLE
How to use it correctly in LuaTeX?

### ISSUE THREAD

**Issue by Thomas01234** [thenumbernine/symmath-lua#5]
I try to use symmath-lua in LuaTeX as described here:
https://tex.stackexchange.com/questions/538836/evaluating-mathematical-expressions-in-lua

But the results are very strange, I show some examples:
`$\sqrt8 = \directlua{tex.sprint(tostring(sym.simplify(sym.sqrt(8))))}$` prints `322`, should print `2*sqrt(2)`.

`$\sin(π/4) = \directlua{tex.sprint(tostring(sym.simplify(sym.sin(sym.pi/4))))}$` prints `pisin()4`, should print `1/2*sqrt(2)`.

However, this expample works: `$\sqrt{72} = \directlua{tex.sprint(tostring(sym.simplify(sym.sqrt(72))))}$` prints correctly `6*sqrt(2)`.

Am I doing something wrong or are there really several bugs? (I can write even more such examples.)

Thanks.
<img width="257" alt="symmath" src="https://user-images.githubusercontent.com/63255189/81122789-fe400780-8f31-11ea-8baa-75fa3d7e0ef7.png">

**Comment by thenumbernine** [comment]
I'm not completely sure what `tex.sprint` is, or what library it comes from.  You shouldn't be seeing `322` or `pisin()4`.

If you use my own serialization functions, listed in the `symmath.export` table, found in symmath.lua, then hopefully it will fix this.  Try the following as inline code:
`$\sqrt8 = \directlua{sym.export.LaTeX(sym.simplify(sym.sqrt(8)))}$`

If you don't want to keep tying `sym.export.LaTeX` then you can preface this all with the statement `sym.tostring = sym.export.LaTeX` and then just use `tostring`:

`$\sqrt8 = \directlua{tostring(sym.simplify(sym.sqrt(8)))}$`

...which most output functions do automatically. I can't speak for `\directlua{}` since I don't have access to it at the moment, but I'm suspicious that, with the `sym.tostring=...` assigned, this might even work:

`$\sqrt8 = \directlua{sym.simplify(sym.sqrt(8))}$`

Also, in writing symmath, I got tired of typing `simplify()` again and again very early on, so I added a shorthand:  If you have a symmath expression then just call it (with no arguments) and it will return the simplified version of itself.  That will look something like this (assuming `\directlua` automatically applies `tostring`):

`$\sqrt8 = \directlua{sym.sqrt(8)()}$`

Here's the output of each of your expressions with a few of my built-in export functions:

```
==================================================
SingleLine
==================================================

2^(3 / 2)

sin(π / 4)

6 √(2)

==================================================
MultiLine
==================================================

 ╭ 3 ╮
 │╶─╴│
 ╰ 2 ╯
2     

     π  
sin(╶─╴)
     4  

6 √(2)

==================================================
LaTeX
==================================================

${2}^{({\frac{3}{2}})}$

$sin\left( {{\frac{1}{4}}{({π})}}\right)$

${{6}} {{\sqrt 2}}$
```

...which looks like...

![image](https://user-images.githubusercontent.com/4241230/81140974-04170680-8f8d-11ea-9aea-8d9502300583.png)

`tex.sprint` aside, I can make it so simplified square roots of integers of positive integer powers look a bit better.  No promises on whether that means 2 sqrt(2) or whether it means sqrt(8).

**Comment by thenumbernine** [comment]
Ok, in the latest version it should look like this now:

![image](https://user-images.githubusercontent.com/4241230/81150342-8c070b80-8fa1-11ea-9a1c-ba04b7bb036c.png)
