### ISSUE TITLE
luarocks install does not work

### ISSUE THREAD

**Issue by flinkow** [thenumbernine/symmath-lua#8]
Simply executing 

```
sudo luarocks install symmath-dev-1.rockspec
```

Leads to this error:

```
Cloning into 'symmath-lua'...
remote: Enumerating objects: 8861, done.
remote: Counting objects: 100% (962/962), done.
remote: Compressing objects: 100% (682/682), done.
remote: Total 8861 (delta 681), reused 505 (delta 272), pack-reused 7899
Receiving objects: 100% (8861/8861), 6.16 MiB | 3.18 MiB/s, done.
Resolving deltas: 100% (7055/7055), done.

symmath dev-1 depends on lua >= 5.1 (5.3-1 provided by VM)
cp: cannot stat 'tests/unit/variable depends.lua': No such file or directory

Error: Build error: Failed installing tests/unit/variable depends.lua in /usr/local/lib/luarocks/rocks-5.3/symmath/dev-1/lua/symmath/tests/unit/variable depends.lua: Failed copying tests/unit/variable depends.lua to /usr/local/lib/luarocks/rocks-5.3/symmath/dev-1/lua/symmath/tests/unit/variable depends.lua
```

which I believe is due to the `.rockspec` file stating in line 249

```
["symmath.tests.unit.variable depends"] = "tests/unit/variable depends.lua"
```

which should correctly be:

```
["symmath.tests.unit.variable depends"] = "tests/unit/Variable dependsOn.lua"
```

Installing the rock works then.

**Comment by thenumbernine** [comment]
Yup, that is the correct fix.  I will fix it soon.  Thanks much.

**Comment by thenumbernine** [comment]
or a better fix would be to keep the source and target files the same filename:

`["symmath.tests.unit.Variable dependsOn"] = "tests/unit/Variable dependsOn.lua"
`

...but you got the idea.

**Comment by thenumbernine** [comment]
That command should work if it is run from the directory of symmath.  It did for me just now.  What sort of error are you seeing?
If it works using a github URL that is good to know.
It won't work in any other directory, or without previously cloning the repo locally, seeing as I haven't uploaded symmath to the official luarocks repository - I only keep a rockspec file in the directory for ease of setup, otherwise you will have to adjust your lua environment variables or lua file locations to get the require's to work.
